### ISSUE TITLE
How to easily create a  Freq vs MassDiff Histogram?

### ISSUE THREAD

**Issue by Alemarcohen** [chhh/FragPipe#57]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [X] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [X] _Open_ search (large precursor mass tolerance)

This is not an ISSUE, rather a question. I'm running MSFragger, and it is working nicely. I analyze my data on the TPP, and add MassDiff to check for possible unexpected mods. To compare different datasets, I export from TPP to excel and try building a Freq vs Mass Diff Histogram. However, Exel is not really good from browsing the histograms (not able to easily zoom in and out axis). Also, when building the histograms for high res insturments (Orbitrap at 90K resolution), the bins are very small, and generating the histogram is cumbersome; bare in mind, I'm not a bioinformatician... :-(

I was wondering if you know any program to generate this type of histograms from the TPP excel file? I've seen this kind of plots on your original MSFragger publication. An implementation of a tool like this would be very convenient to the proteomics community.

THANKS!

Alejandro

**Comment by chhh** [comment]
Hi Alejandro, we do have such a tool. Shoot me an email to dmitriya at umich edu for a test version.

Best,
Dmitry
