### ISSUE TITLE
Is there a protocol for the use of  MSFragger-GUI?

### ISSUE THREAD

**Issue by bprcptm** [chhh/FragPipe#59]
subj

**Comment by chhh** [comment]
I'm sorry I didn't understand the question.
Is that a question about usage? Configure the paths to downloaded binaries of MSFragger and Philosopher on the Config tab (there are buttons for downloads). Then drag and drop your mzML or mzXML files on the LCMS tab, specify protein database in Sequence Db tab (again, there are instructions on the tab). That's the bare minimum - you can now go to the last tab and click Run.

**Comment by chhh** [comment]
No response
