### ISSUE TITLE
Visualization the result of MSFragger

### ISSUE THREAD

**Issue by wenbostar** [chhh/FragPipe#66]
Is there any tool which can be used to visualize the pepXML result of MSFragger?
Bo

**Comment by andytyk** [comment]
@chhh Dmitry has a tool for plotting and visualizing the mass shifts in the pepXML results.  It's not released yet but perhaps he can share a beta version with you.

**Comment by anesvi** [comment]
I was not sure what Bo wanted to visualize. I assumed MS/MS spectra…
**********************************************************
Electronic Mail is not secure, may not be read every day, and should not be used for urgent or sensitive issues

**Comment by wenbostar** [comment]
Hi Alexey,

Yes, you're right. I want to visualize the MS/MS spectra with peptide annotated. It looks like there is no modification position information for PSMs in the pepXML from open search. I used the [PDV](https://github.com/wenbostar/PDV) to visualize the pepXML generated by MSFragger. But I cannot find the modifications from open search.

Bo

**Comment by anesvi** [comment]
Thanks Bo. This looks very useful. We had multiple requests for how to visualize the spectra and your tool looks like the answer!
With open searching, the mass shift is initially not localized to any amino acid. But we can do that using a site localization tool such as PTMProphet or other tools we have in our pipeline. PTMProphet (or other localization tools) are not a part of MSFragger-GUI now, but we would like to add them there.  It would be great if we can work with you to implement a full support for MSFragger open search results in PDV.

Will you be at ASMS?
We all will be there and can discuss.

Best,
Alexey

**Comment by wenbostar** [comment]
Hi Alexey,

It should be easy to implement a full support for MSFragger as long as the modification sites are determined. I'm really happy to do this with you. As you can see in [the manual of PDV](http://pdv.zhang-lab.org/data/download/PDV-Manual.pdf), currently PDV supports multiple different identification formats. We're happy to support more. I will attend the ASMS meeting. Let us discuss there.

Bo
