### ISSUE TITLE
 workspace not found 

### ISSUE THREAD

**Issue by assafkacen** [chhh/FragPipe#74]
# Describe the problem
Hello
I get the error message: " workspace not found" after finishing calculating spectral count. I saw an open issue about the same problem but fail to find the solution. 

* **I'm submitting a:**
  - [x ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ x] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

### Genral proteomics experiment description
non specific digestion 
...

### Sequence database

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

output log 👍 
INFO[18:09:06] Executing Workspace 20180808
INFO[18:09:08] Removing workspace
INFO[18:09:08] Done
INFO[18:09:08] Executing Workspace 20180808
INFO[18:09:09] Creating workspace
INFO[18:09:09] Done
INFO[18:09:09] Executing PeptideProphet 20180808
 file 1: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1701_1_010718.pepXML
Failed to open input file '/home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1701_1_010718.mzXML'.
WARNING: cannot open data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1701_1_010718.mzXML in msms_run_summary tag... trying .mzML ...
SUCCESS: CORRECTED data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1701_1_010718.mzML in msms_run_summary tag...
 processed altogether 190 results
INFO: Results written to file: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1701_1_010718.pep.xml

  - /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1701_1_010718.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Not using ntt model
Not using nmc model
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

adding ACCMASS mixture distribution
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 68 2+, 92 3+, 27 4+, 3 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 55 Decoys, and 135 Non-Decoys
Iterations: .........10.........20....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 25 iterations
INFO[18:09:12] Done
INFO[18:09:12] Executing PeptideProphet 20180808
 file 1: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1702_1_010718.pepXML
Failed to open input file '/home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1702_1_010718.mzXML'.
WARNING: cannot open data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1702_1_010718.mzXML in msms_run_summary tag... trying .mzML ...
SUCCESS: CORRECTED data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1702_1_010718.mzML in msms_run_summary tag...
 processed altogether 71 results
INFO: Results written to file: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1702_1_010718.pep.xml

  - /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1702_1_010718.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Not using ntt model
Not using nmc model
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

adding ACCMASS mixture distribution
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 14 2+, 47 3+, 9 4+, 0 5+, 1 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 27 Decoys, and 44 Non-Decoys
Iterations: .........10.........20....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 25 iterations
INFO[18:09:13] Done
INFO[18:09:13] Executing PeptideProphet 20180808
 file 1: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1704_1_010718.pepXML
Failed to open input file '/home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1704_1_010718.mzXML'.
WARNING: cannot open data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1704_1_010718.mzXML in msms_run_summary tag... trying .mzML ...
SUCCESS: CORRECTED data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1704_1_010718.mzML in msms_run_summary tag...
 processed altogether 394 results
INFO: Results written to file: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1704_1_010718.pep.xml

  - /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1704_1_010718.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Not using ntt model
Not using nmc model
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

adding ACCMASS mixture distribution
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 210 2+, 124 3+, 33 4+, 18 5+, 5 6+, and 4 7+ spectra.
Initialising statistical models ...
Found 94 Decoys, and 300 Non-Decoys
Iterations: .........10.........20....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 25 iterations
INFO[18:09:17] Done
INFO[18:09:17] Executing PeptideProphet 20180808
 file 1: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1703_1_010718.pepXML
Failed to open input file '/home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1703_1_010718.mzXML'.
WARNING: cannot open data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1703_1_010718.mzXML in msms_run_summary tag... trying .mzML ...
SUCCESS: CORRECTED data file /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1703_1_010718.mzML in msms_run_summary tag...
 processed altogether 267 results
INFO: Results written to file: /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1703_1_010718.pep.xml

  - /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1703_1_010718.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Not using ntt model
Not using nmc model
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

adding ACCMASS mixture distribution
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 146 2+, 88 3+, 21 4+, 8 5+, 4 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 58 Decoys, and 209 Non-Decoys
Iterations: .........10.........20....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 25 iterations
INFO[18:09:19] Done
INFO[18:09:19] Executing ProteinProphet 20180808
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705221614-exported (Linux-x86_64))
 (no FPKM) (using degen pep info)
Reading in /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1701_1_010718.pep.xml...
...read in 0 1+, 44 2+, 14 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1702_1_010718.pep.xml...
...read in 0 1+, 0 2+, 2 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1703_1_010718.pep.xml...
...read in 0 1+, 81 2+, 28 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-HF2_7696_YMER_1704_1_010718.pep.xml...
...read in 0 1+, 0 2+, 38 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Initializing 187 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........37000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........41000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........42000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........43000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........44000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........45000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........46000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........47000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........48000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........49000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........50000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........51000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........52000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........53000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........54000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........55000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........56000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........57000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........58000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........59000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........60000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........61000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........62000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........63000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........64000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........65000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........66000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........67000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........68000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........69000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........70000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........71000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........72000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........73000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........74000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........75000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........76000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........77000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........78000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........79000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........80000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........81000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........82000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........83000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........84000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........85000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........86000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........87000
.........:.........:.........:.........:.........:  Total: 87507
Computing degenerate peptides for 164 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 183 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 183 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 183 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing 116 protein groups: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating sensitivity...and error tables...
Computing MU for 183 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=3.25341e-07, db_size=91247603

Finished
INFO[18:09:22] Done
INFO[18:09:22] Executing Database 20180808
INFO[18:09:22] Processing database
INFO[18:09:36] Done
INFO[18:09:36] Executing Filter 20180808
INFO[18:09:36] Processing peptide identification files
INFO[18:09:36] 1+ Charge profile                             decoy=0 target=0
INFO[18:09:36] 2+ Charge profile                             decoy=11 target=142
INFO[18:09:36] 3+ Charge profile                             decoy=31 target=106
INFO[18:09:36] 4+ Charge profile                             decoy=0 target=0
INFO[18:09:36] 5+ Charge profile                             decoy=0 target=0
INFO[18:09:36] 6+ Charge profile                             decoy=0 target=0
INFO[18:09:36] Database search results                       ions=262 peptides=252 psms=290
INFO[18:09:36] Converged to 0.00 % FDR with 0 PSMs           decoy=0 threshold=10 total=0
INFO[18:09:36] Converged to 0.00 % FDR with 0 Peptides       decoy=0 threshold=10 total=0
INFO[18:09:36] Converged to 0.00 % FDR with 0 Ions           decoy=0 threshold=10 total=0
INFO[18:09:37] Post processing identifications
INFO[18:09:38] Processing Protein Inference
INFO[18:09:38] Correcting PSM to Protein mappings
INFO[18:09:38] Mapping Ion status to PSMs
INFO[18:09:38] Calculating Spectral Counts
FATA[18:09:38] workspace not found. Run 'philosopher workspace --init' to create one or execute the command inside a workspace directory
INFO[18:09:38] Executing Report 20180808
FATA[18:09:38] cannot restore serialized data structures: invalid argument
INFO[18:09:39] Executing Workspace 20180808
INFO[18:09:40] Removing workspace
INFO[18:09:40] Done
```
** copy text from the text console in the gui here **
```
I am running the philosopher commands from a command line: 
command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 workspace --clean
 command :/home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 workspace --init
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 peptideprophet --decoy rev_ --enzyme N --decoyprobs --ppm --accmass --nonparam --expectscore --nonmc --nontt --database /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1701_1_010718.pepXML
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 peptideprophet --decoy rev_ --enzyme N --decoyprobs --ppm --accmass --nonparam --expectscore --nonmc --nontt --database /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1702_1_010718.pepXML
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 peptideprophet --decoy rev_ --enzyme N --decoyprobs --ppm --accmass --nonparam --expectscore --nonmc --nontt --database /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1704_1_010718.pepXML
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 peptideprophet --decoy rev_ --enzyme N --decoyprobs --ppm --accmass --nonparam --expectscore --nonmc --nontt --database /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/HF2_7696_YMER_1703_1_010718.pepXML
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 proteinprophet --output interact /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/interact-*.pep.xml 
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 database --annotate /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/mutatedSeqsUniprotName.translated.withFusion.fasta --prefix rev_
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 filter --tag rev_ --sequential --pepxml /home/labs/yifatlab/assafk/modification/Galit/Base/MSFragger/combine/
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 report
 command : /home/labs/yifatlab/assafk/tools/MSFragger_20170103/philosopher_linux_amd64 workspace --clean

**Comment by anesvi** [comment]
Hi,
I see you are running an old version of MSFragger. Please try with a new version.
Also, I am not sure what version of Philosopher you are running. Felipe (cc’ed) can help with that.
Alexey

**Comment by assafkacen** [comment]
sorry I didn't include it in the initial report:

MSFragger version MSFragger-20180316
MSFTBX version 1.8.2
(c) University of Michigan

System OS: Linux, Architecture: amd64
Java Info: 1.8.0_121, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 50062MB memory

the philosopher version , as far as I know is the latest version.

**Comment by prvst** [comment]
@assafkacen 
I don't know why you are having an issue with the workspace, maybe @chhh can take a look into the GUI back end. Nevertheless, it looks t me that your database search failed, or you don't have enough spectra in your files.

**Comment by chhh** [comment]
@assafkacen Do I understand this correctly, that you're having the problem while running the commands from the command line?
And the command sequence is 
```
philosopher workspace --clean
philosopher workspace --init
philosopher peptideprophet ... 1701_1_010718.pepXML
philosopher peptideprophet ... 1702_1_010718.pepXML
philosopher peptideprophet ... 1703_1_010718.pepXML
philosopher peptideprophet ... 1704_1_010718.pepXML
philosopher proteinprophet --output interact .../interact-*.pep.xml
philosopher database --annotate ...withFusion.fasta --prefix rev_
philosopher filter --tag rev_ --sequential --pepxml .../combine/
philosopher report
philosopher workspace --clean
```

**Comment by chhh** [comment]
@assafkacen I guess then the problem likely was an old version of philosopher
