### ISSUE TITLE
Label-free quantification

### ISSUE THREAD

**Issue by marcisaksson** [chhh/FragPipe#80]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
Hi,

I have run several raw-files in fragPipe with an open search, and I enabled label-free quantification. According to my understanding, spectral counts are used for this quantification right? 

The problem is, I don't know where I can extract the spectral counts from different files (samples), for the relative quantification? The report.tsv-file seems to report the total number of spectral counts from all runs which is not very useful for me. I would like to separate the samples/runs into two groups, and run a t-test to find differentially expressed proteins using the spectral counts.

Last thing, how to best deal with the normalization of the spectral counts prior to running a t-test?

Best,

Marc 

## System info

You can find that printed on the _Config_ tab.
- OS and version: ** _your response here_ **
- Java version: ** _your response here_ **

----

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"

...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **

### Sequence database

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

** _You can find it in the output directory you specified for analysis._ **

## Run log output

```
** copy text from the text console in the gui here **
```

**Comment by prvst** [comment]
@marcisaksson 

Unfortunately fragpipe does not provide a way to analyze your files in a separate way, I guess you would have to run the program multiple times, one for each sample or group of files. If you are OK with running programs on the command line, you might want to give a try to Philosopher, it allows you to separate your spectra files into groups or samples.

**Comment by marcisaksson** [comment]
I understand. I guess it could be put on a 'to do list' for fragPipe, since it integrates msFragger and Philosopher already. It would be neat to have the option to set an experimental design as in MaxQuant, resulting in an output with quantitative intensities for each samples (similar to LFQ intensities in MaxQuant). In the mean time, I will look into running philosopher with cmd, even if I am an absolute beginner.

**Comment by chhh** [comment]
@marcisaksson So the feature you want is to be able to group sets of input LCMS files?

**Comment by chhh** [comment]
@marcisaksson Also, to simplify your start with running everything from the command line, in FragPipe check the `Dry run` checkbox next to the `Run` button, and click `Run`. It will just print the commands to the text console, so you can copy paste them into your scripts as a starting point.

**Comment by chhh** [comment]
This is related to #31

**Comment by marcisaksson** [comment]
Actually, it's more like being able to add the files as separate samples in fragPipe. The report.tsv file could then report the sample specific spectral counts even if it might mean many extra columns. This is similar to what happens in MaxQuant with LFQ intensity columns, when setting different sample/experiment names to the raw files.

**Comment by chhh** [comment]
@marcisaksson So it's a little more. You want to be able to label single files - call it sets, experiments, samples - it's some way of `group`ing input LCMS files. Then produce a combined report which includes columns for each `group`.
@prvst Does philosopher support that? Sounds like a good feature to have - comparative analysis is very common.

**Comment by marcisaksson** [comment]
Yes, we could call it grouping. I will continue with the MaxQuant analogy here :) In MaxQuant, you are able to set individual experiment names to individual raw-files. That will produce LFQ intensity columns for each individual run. 

Alternatively, you can set the same experiment name to several raw-files (in case of prefractionated injections from a single sample, or technical replicates). In the latter case, MaxQuant will sum the intensity for these runs and produce one LFQ intensity column (since the experiment name is the same).

 That is a feature I like, but I don´t know how difficult it is to implement, especially if there should be normalizing steps prior to summing the counts for the raw files having the same experiment name.

**Comment by chhh** [comment]
Fixed in v8.4 (not yet publicly released)
