### ISSUE TITLE
incorrect nonspecific search defaults

### ISSUE THREAD

**Issue by anesvi** [chhh/FragPipe#82]
The latest FragPipe release contains incorrect defaults for nonspecific searches:

1. In MSFragger search tab, need to change Cleavage to NON-SPECIFIC

2. In PeptideProphet tab, please use the same options as for regular closed search
--decoy rev_ --decoyprobs --ppm --accmass --nonparam --expectscore

We should fix this in the next release

Alexey

**Comment by chhh** [comment]
included in updated fragger tab branch
