### ISSUE TITLE
MSFragger issues

### ISSUE THREAD

**Issue by har-wradim** [chhh/FragPipe#87]
* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

Is there a separate issue tracker for MSFragger (CLI) or are all issues on-topic here? A related question: will MSFragger's source be released in the future and have its own repository with PRs etc?

**Comment by anesvi** [comment]
There is no separate issue tracker for MSFragger at the moment. So for now this is the best place to post all questions related to MSFragger.  We are discussing options for creating a  separate site or improving/expanding this site. MSFragger is not currently available as an open source (which may change in the future), but we do have ability to implement new methods and improvements as a collaboration if of mutual interest.
Best,
Alexey

**Comment by har-wradim** [comment]
OK, thanks for the comprehensive response.
